# Selected device 8
# Generated by uvusbreplay 0.1
# uvusbreplay copyright 2011 John McMaster <JohnDMcMaster@gmail.com>
# cmd: /home/mcmaster/bin/usbrply --device-hi ham/2019-12-26_02_init.pcapng --wrapper --vid 0x0661 --pid 0xa802

import binascii
import time
import usb1
from uvscada.util import hexdump

def validate_read(expected, actual, msg):
    if expected != actual:
        print 'Failed %s' % msg
        print '  Expected; %s' % binascii.hexlify(expected,)
        print '  Actual:   %s' % binascii.hexlify(actual,)
        #raise Exception('failed validate: %s' % msg)


def replay(dev):
    def bulkRead(endpoint, length, timeout=None):
        ret = dev.bulkRead(endpoint, length, timeout=(1000 if timeout is None else timeout))
        print('')
        hexdump(ret, label='bulkRead(%u)' % length, indent='')
        return ret

    def bulkWrite(endpoint, data, timeout=None):
        dev.bulkWrite(endpoint, data, timeout=(1000 if timeout is None else timeout))
    
    def controlRead(request_type, request, value, index, length,
                    timeout=None):
        return dev.controlRead(request_type, request, value, index, length,
                    timeout=(1000 if timeout is None else timeout))

    def controlWrite(request_type, request, value, index, data,
                     timeout=None):
        dev.controlWrite(request_type, request, value, index, data,
                     timeout=(1000 if timeout is None else timeout))


    # Generated from packet 209/210
    bulkWrite(0x01, "\x00\x00\x00\x00\x00\x00\x00\x00")
    # Generated from packet 211/212
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x01", buff, "packet 211/212")
    # Generated from packet 213/214
    bulkWrite(0x01, "\x00\x00\x00\x01\x00\x00\x00\x00")
    # Generated from packet 215/216
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x48\x41\x4D\x41\x4D\x41\x54\x53\x55\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x43\x39\x37\x33\x30\x44\x4B\x2D\x31\x31\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x31\x2E\x32\x31\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x35\x34\x30\x33\x32\x31\x39\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 215/216")
    # Generated from packet 217/218
    bulkWrite(0x01, "\x00\x00\x00\x02\x00\x00\x00\x00")
    # Generated from packet 219/220
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x00\x14\x00\x00\x04\x08\x00\x00\x04\x08\x00\x00\x00\x10"
            "\x00\x00\x00\x01", buff, "packet 219/220")
    # Generated from packet 221/222
    bulkWrite(0x01, "\x00\x00\x00\x24\x00\x00\x00\x00")
    # Generated from packet 223/224
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x00\x06\x00\x00\x00\x20\x00\x00\x00\x03", buff, "packet 223/224")
    # Generated from packet 225/226
    bulkWrite(0x01, "\x00\x00\x00\x2A\x00\x00\x00\x00")
    # Generated from packet 227/228
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 227/228")
    # Generated from packet 229/230
    bulkWrite(0x01, "\x00\x00\x00\x39\x00\x00\x00\x00")
    # Generated from packet 231/232
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 231/232")
    # Generated from packet 233/234
    bulkWrite(0x01, "\x00\x00\x00\x3A\x00\x00\x00\x00")
    # Generated from packet 235/236
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 235/236")
    # Generated from packet 237/238
    bulkWrite(0x01, "\x00\x00\x00\x3B\x00\x00\x00\x00")
    # Generated from packet 239/240
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 239/240")
    # Generated from packet 241/242
    bulkWrite(0x01, "\x00\x00\x00\x3C\x00\x00\x00\x00")
    # Generated from packet 243/244
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 243/244")
    # Generated from packet 245/246
    bulkWrite(0x01, "\x00\x00\x00\x3D\x00\x00\x00\x00")
    # Generated from packet 247/248
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 247/248")
    # Generated from packet 249/250
    bulkWrite(0x01, "\x00\x00\x00\x4A\x00\x00\x00\x00")
    # Generated from packet 251/252
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 251/252")
    # Generated from packet 253/254
    bulkWrite(0x01, "\x00\x00\x00\x4F\x00\x00\x00\x00")
    # Generated from packet 255/256
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 255/256")
    # Generated from packet 257/258
    bulkWrite(0x01, "\x00\x00\x00\x23\x00\x00\x00\x00")
    # Generated from packet 259/260
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x01", buff, "packet 259/260")
    # Generated from packet 261/262
    bulkWrite(0x01, "\x00\x00\x00\x29\x00\x00\x00\x00")
    # Generated from packet 263/264
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 263/264")
    # Generated from packet 265/266
    bulkWrite(0x01, "\x00\x00\x00\x01\x00\x00\x00\x00")
    # Generated from packet 267/268
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x48\x41\x4D\x41\x4D\x41\x54\x53\x55\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x43\x39\x37\x33\x30\x44\x4B\x2D\x31\x31\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x31\x2E\x32\x31\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x35\x34\x30\x33\x32\x31\x39\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 267/268")
    # Generated from packet 269/270
    bulkWrite(0x01, "\x00\x00\x00\x01\x00\x00\x00\x00")
    # Generated from packet 271/272
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x48\x41\x4D\x41\x4D\x41\x54\x53\x55\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x43\x39\x37\x33\x30\x44\x4B\x2D\x31\x31\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x31\x2E\x32\x31\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x35\x34\x30\x33\x32\x31\x39\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 271/272")
    # Generated from packet 273/274
    bulkWrite(0x01, "\x00\x00\x00\x01\x00\x00\x00\x00")
    # Generated from packet 275/276
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x48\x41\x4D\x41\x4D\x41\x54\x53\x55\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x43\x39\x37\x33\x30\x44\x4B\x2D\x31\x31\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x31\x2E\x32\x31\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x35\x34\x30\x33\x32\x31\x39\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 275/276")
    # Generated from packet 277/278
    bulkWrite(0x01, "\x00\x00\x00\x09\x00\x00\x00\x0A\x00\x01\x00\x00\x00\x00\x04\x08"
            "\x04\x08")
    # Generated from packet 279/280
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x01", buff, "packet 279/280")
    # Generated from packet 281/282
    bulkWrite(0x01, "\x00\x00\x00\x04\x00\x00\x00\x00")
    # Generated from packet 283/284
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x04\x08\x00\x00\x04\x08", buff, "packet 283/284")
    # Generated from packet 285/286
    bulkWrite(0x01, "\x00\x00\x00\x2E\x00\x00\x00\x04\x00\x00\x00\x02")
    # Generated from packet 287/288
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 287/288")
    # Generated from packet 289/290
    bulkWrite(0x01, "\x00\x00\x00\x2E\x00\x00\x00\x04\x00\x00\x00\x12")
    # Generated from packet 291/292
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 291/292")
    # Generated from packet 293/294
    bulkWrite(0x01, "\x00\x00\x00\x2E\x00\x00\x00\x04\x00\x00\x00\x18")
    # Generated from packet 295/296
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 295/296")
    # Generated from packet 297/298
    bulkWrite(0x01, "\x00\x00\x00\x21\x00\x00\x00\x04\x00\x00\x00\x00")
    # Generated from packet 299/300
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x3F\x9E\xB8\x51\xEB\x85\x1E\xB8", buff, "packet 299/300")
    # Generated from packet 301/302
    bulkWrite(0x01, "\x00\x00\x00\x21\x00\x00\x00\x04\x00\x00\x00\x01")
    # Generated from packet 303/304
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x40\x34\x00\x00\x00\x00\x00\x00", buff, "packet 303/304")
    # Generated from packet 305/306
    bulkWrite(0x01, "\x00\x00\x00\x21\x00\x00\x00\x04\x00\x00\x00\x02")
    # Generated from packet 307/308
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x3F\x50\x62\x4D\xD2\xF1\xA9\xFC", buff, "packet 307/308")
    # Generated from packet 309/310
    bulkWrite(0x01, "\x00\x00\x00\x21\x00\x00\x00\x04\x00\x00\x00\x03")
    # Generated from packet 311/312
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 311/312")
    # Generated from packet 313/314
    bulkWrite(0x01, "\x00\x00\x00\x20\x00\x00\x00\x04\x00\x00\x07\xD0")
    # Generated from packet 315/316
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x01", buff, "packet 315/316")
    # Generated from packet 317/318
    bulkWrite(0x01, "\x00\x00\x00\x1F\x00\x00\x00\x00")
    # Generated from packet 319/320
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x07\xD0", buff, "packet 319/320")
    # Generated from packet 321/322
    bulkWrite(0x01, "\x00\x00\x00\x20\x00\x00\x00\x04\x00\x00\x00\xFA")
    # Generated from packet 323/324
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x01", buff, "packet 323/324")
    # Generated from packet 325/326
    bulkWrite(0x01, "\x00\x00\x00\x1F\x00\x00\x00\x00")
    # Generated from packet 327/328
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x00\xFA", buff, "packet 327/328")
    # Generated from packet 329/330
    bulkWrite(0x01, "\x00\x00\x00\x20\x00\x00\x00\x04\x00\x00\x00\xFA")
    # Generated from packet 331/332
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x01", buff, "packet 331/332")
    # Generated from packet 333/334
    bulkWrite(0x01, "\x00\x00\x00\x1F\x00\x00\x00\x00")
    # Generated from packet 335/336
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x00\xFA", buff, "packet 335/336")
    # Generated from packet 337/338
    bulkWrite(0x01, "\x00\x00\x00\x2D\x00\x00\x00\x02\x00\x01")
    # Generated from packet 339/340
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 339/340")
    # Generated from packet 341/342
    bulkWrite(0x01, "\x00\x00\x00\x1F\x00\x00\x00\x00")
    # Generated from packet 343/344
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x00\xFA", buff, "packet 343/344")
    # Generated from packet 345/346
    bulkWrite(0x01, "\x00\x00\x00\x2E\x00\x00\x00\x04\x00\x00\x00\x12")
    # Generated from packet 347/348
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 347/348")
    # Generated from packet 349/350
    bulkWrite(0x01, "\x00\x00\x00\x2E\x00\x00\x00\x04\x00\x00\x00\x02")
    # Generated from packet 351/352
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 351/352")
    # Generated from packet 353/354
    bulkWrite(0x01, "\x00\x00\x00\x20\x00\x00\x00\x04\x00\x00\x00\xFA")
    # Generated from packet 355/356
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x01", buff, "packet 355/356")
    # Generated from packet 357/358
    bulkWrite(0x01, "\x00\x00\x00\x1F\x00\x00\x00\x00")
    # Generated from packet 359/360
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x00\xFA", buff, "packet 359/360")
    # Generated from packet 361/362
    bulkWrite(0x01, "\x00\x00\x00\x2D\x00\x00\x00\x02\x00\x01")
    # Generated from packet 363/364
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 363/364")













    bulkWrite(0x01, "\x00\x00\x00\x09\x00\x00\x00\x0A\x00\x01\x00\x00\x00\x00\x04\x08"
                "\x04\x08")
    # Generated from packet 29/30
    buff = bulkRead(0x83, 0x0200)
    print("buf size: %u" % len(buff))
    # Generated from packet 31/32
    bulkWrite(0x01, "\x00\x00\x00\x04\x00\x00\x00\x00")
    # Generated from packet 33/34
    buff = bulkRead(0x83, 0x0200)
    print("buf size: %u" % len(buff))
    # Generated from packet 35/36
    bulkWrite(0x01, "\x00\x00\x00\x09\x00\x00\x00\x0A\x00\x01\x00\x00\x00\x00\x04\x08"
                "\x04\x08")
    # Generated from packet 37/38
    buff = bulkRead(0x83, 0x0200)
    print("buf size: %u" % len(buff))
    # Generated from packet 39/40
    bulkWrite(0x01, "\x00\x00\x00\x04\x00\x00\x00\x00")
    # Generated from packet 41/42
    buff = bulkRead(0x83, 0x0200)
    print("buf size: %u" % len(buff))
    # Generated from packet 43/44
    bulkWrite(0x01, "\x00\x00\x00\x04\x00\x00\x00\x00")
    # Generated from packet 45/46
    buff = bulkRead(0x83, 0x0200)
    print("buf size: %u" % len(buff))
    # Generated from packet 47/48
    bulkWrite(0x01, "\x00\x00\x00\x0E\x00\x00\x00\x01\x01")
    # Generated from packet 49/50
    buff = bulkRead(0x83, 0x0200)
    print("buf size: %u" % len(buff))


    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 54/85
    buff = bulkRead(0x82, 0x3200)
    # Generated from packet 86/87
    buff = bulkRead(0x82, 0x1C00)
    # Generated from packet 91/91
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 88/121
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 89/122
    buff = bulkRead(0x82, 0x0E00)
    # Generated from packet 90/123
    buff = bulkRead(0x82, 0x4000)
    # WARNING: Packet 124 missing submit.  URB ID: 0xFFFF97DCEC875CC0
    # Generated from packet 92/125
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 93/126
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 94/127
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 95/128
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 96/129
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 97/130
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 98/131
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 99/132
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 100/133
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 101/134
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 102/135
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 103/136
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 104/137
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 105/138
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 106/139
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 107/140
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 108/141
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 109/142
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 110/143
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 111/144
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 112/145
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 113/146
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 114/147
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 115/148
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 116/149
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 117/150
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 118/151
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 119/152
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 120/153
    buff = bulkRead(0x82, 0x3200)
    # Generated from packet 154/187
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 155/188
    buff = bulkRead(0x82, 0x0E00)
    # Generated from packet 156/189
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 157/190
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 158/191
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 159/192
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 160/193
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 161/194
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 162/195
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 163/196
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 164/197
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 165/198
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 166/199
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 167/200
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 168/201
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 169/202
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 170/203
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 171/204
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 172/205
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 173/206
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 174/207
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 175/208
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 176/209
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 177/210
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 178/211
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 179/212
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 180/213
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 181/214
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 182/215
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 183/216
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 184/217
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 185/218
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 186/219
    buff = bulkRead(0x82, 0x3200)
    # Generated from packet 220/253
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 221/254
    buff = bulkRead(0x82, 0x0E00)
    # Generated from packet 222/255
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 223/256
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 224/257
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 225/258
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 226/259
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 227/260
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 228/261
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 229/262
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 230/263
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 231/264
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 232/265
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 233/266
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 234/267
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 235/268
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 236/269
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 237/270
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 238/271
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 239/272
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 240/273
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 241/274
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 242/275
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 243/276
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 244/277
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 245/278
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 246/279
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 247/280
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 248/281
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 249/282
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 250/283
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 251/284
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 252/285
    buff = bulkRead(0x82, 0x3200)
    # Generated from packet 286/289
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 287/290
    buff = bulkRead(0x82, 0x0E00)
    # Generated from packet 288/291
    buff = bulkRead(0x82, 0x3600)
    # Generated from packet 292/293
    buff = bulkRead(0x82, 0x0200)
    # Generated from packet 294/295
    buff = bulkRead(0x82, 0x0200)
    # Generated from packet 296/329
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 297/330
    buff = bulkRead(0x82, 0x0E00)
    # Generated from packet 298/331
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 299/332
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 300/333
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 301/334
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 302/335
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 303/336
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 304/337
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 305/338
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 306/339
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 307/340
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 308/341
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 309/342
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 310/343
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 311/344
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 312/345
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 313/346
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 314/347
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 315/348
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 316/349
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 317/350
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 318/351
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 319/352
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 320/353
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 321/354
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 322/355
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 323/356
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 324/357
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 325/358
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 326/359
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 327/360
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 328/361
    buff = bulkRead(0x82, 0x3200)
    # Generated from packet 362/395
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 363/396
    buff = bulkRead(0x82, 0x0E00)
    # Generated from packet 364/397
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 365/398
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 366/399
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 367/400
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 368/401
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 369/402
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 370/403
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 371/404
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 372/405
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 373/406
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 374/407
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 375/408
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 376/409
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 377/410
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 378/411
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 379/412
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 380/413
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 381/414
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 382/415
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 383/416
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 384/417
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 385/418
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 386/419
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 387/420
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 388/421
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 389/422
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 390/423
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 391/424
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 392/425
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 393/426
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 394/427
    buff = bulkRead(0x82, 0x3200)
    # Generated from packet 428/461
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 429/462
    buff = bulkRead(0x82, 0x0E00)
    # Generated from packet 430/463
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 431/464
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 432/465
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 433/466
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 434/467
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 435/468
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 436/469
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 437/470
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 438/471
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 439/472
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 440/473
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 441/474
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 442/475
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 443/476
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 444/477
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 445/478
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 446/479
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 447/480
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 448/481
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 449/482
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 450/483
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 451/484
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 452/485
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 453/486
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 454/487
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 455/488
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 456/489
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 457/490
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 458/491
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 459/492
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 460/493
    buff = bulkRead(0x82, 0x3200)
    # Generated from packet 494/527
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 495/528
    buff = bulkRead(0x82, 0x0E00)
    # Generated from packet 496/529
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 497/530
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 498/531
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 499/532
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 500/533
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 501/534
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 502/535
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 503/536
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 504/537
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 505/538
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 506/539
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 507/540
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 508/541
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 509/542
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 510/543
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 511/544
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 512/545
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 513/546
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 514/547
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 515/548
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 516/549
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 517/550
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 518/551
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 519/552
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 520/553
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 521/554
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 522/555
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 523/556
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 524/557
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 525/558
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 526/559
    buff = bulkRead(0x82, 0x3200)
    # Generated from packet 560/563
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 561/564
    buff = bulkRead(0x82, 0x0E00)
    # Generated from packet 562/565
    buff = bulkRead(0x82, 0x3600)
    # Generated from packet 566/567
    buff = bulkRead(0x82, 0x0200)
    # Generated from packet 568/569
    buff = bulkRead(0x82, 0x0200)
    # Generated from packet 570/603
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 571/604
    buff = bulkRead(0x82, 0x0E00)
    # Generated from packet 572/605
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 573/606
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 574/607
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 575/608
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 576/609
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 577/610
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 578/611
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 579/612
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 580/613
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 581/614
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 582/615
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 583/616
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 584/617
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 585/618
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 586/619
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 587/620
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 588/621
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 589/622
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 590/623
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 591/624
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 592/625
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 593/626
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 594/627
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 595/628
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 596/629
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 597/630
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 598/631
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 599/632
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 600/633
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 601/634
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 602/635
    buff = bulkRead(0x82, 0x3200)
    # Generated from packet 660/660
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 661/661
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 662/662
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 663/663
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 664/664
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 665/665
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 666/666
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 667/667
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 668/668
    buff = bulkRead(0x82, 0x3200)
    # WARNING: req max 12800 but got 16384
    # Generated from packet 636/669
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 637/670
    buff = bulkRead(0x82, 0x0E00)
    # Generated from packet 638/671
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 639/672
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 640/673
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 641/674
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 642/675
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 643/676
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 644/677
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 645/678
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 646/679
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 647/680
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 648/681
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 649/682
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 650/683
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 651/684
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 652/685
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 653/686
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 654/687
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 655/688
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 656/689
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 657/690
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 658/691
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 659/692
    buff = bulkRead(0x82, 0x4000)
    # WARNING: Packet 693 missing submit.  URB ID: 0xFFFF97DC8CA36A80
    # WARNING: Packet 694 missing submit.  URB ID: 0xFFFF97DC8CA36F00
    # WARNING: Packet 695 missing submit.  URB ID: 0xFFFF97DC8CA36180
    # WARNING: Packet 696 missing submit.  URB ID: 0xFFFF97DC8CA363C0
    # WARNING: Packet 697 missing submit.  URB ID: 0xFFFF97DC8CA36480
    # WARNING: Packet 698 missing submit.  URB ID: 0xFFFF97DC8CA36B40
    # WARNING: Packet 699 missing submit.  URB ID: 0xFFFF97DC8CA36C00
    # WARNING: Packet 700 missing submit.  URB ID: 0xFFFF97DDB2564E40
    # WARNING: Packet 701 missing submit.  URB ID: 0xFFFF97DDB2564780
    # Generated from packet 702/735
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 703/736
    buff = bulkRead(0x82, 0x0E00)
    # Generated from packet 704/737
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 705/738
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 706/739
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 707/740
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 708/741
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 709/742
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 710/743
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 711/744
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 712/745
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 713/746
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 714/747
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 715/748
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 716/749
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 717/750
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 718/751
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 719/752
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 720/753
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 721/754
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 722/755
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 723/756
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 724/757
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 725/758
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 726/759
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 727/760
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 728/761
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 729/762
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 730/763
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 731/764
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 732/765
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 733/766
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 734/767
    buff = bulkRead(0x82, 0x3200)
    # Generated from packet 768/801
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 769/802
    buff = bulkRead(0x82, 0x0E00)
    # Generated from packet 770/803
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 771/804
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 772/805
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 773/806
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 774/807
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 775/808
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 776/809
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 777/810
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 778/811
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 779/812
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 780/813
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 781/814
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 782/815
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 783/816
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 784/817
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 785/818
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 786/819
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 787/820
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 788/821
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 789/822
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 790/823
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 791/824
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 792/825
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 793/826
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 794/827
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 795/828
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 796/829
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 797/830
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 798/831
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 799/832
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 800/833
    buff = bulkRead(0x82, 0x3200)
    # Generated from packet 834/837
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 835/838
    buff = bulkRead(0x82, 0x0E00)
    # Generated from packet 836/839
    buff = bulkRead(0x82, 0x3600)
    # Generated from packet 840/840
    buff = bulkRead(0x82, 0x0200)
    # WARNING: req max 512 but got 12800
    # WARNING: Packet 841 missing submit.  URB ID: 0xFFFF97DDB2564780
    # Generated from packet 842/843
    bulkWrite(0x01, "\x00\x00\x00\x0F\x00\x00\x00\x00")
    # Generated from packet 844/845
    buff = bulkRead(0x82, 0x0200)
    # Generated from packet 846/850
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 847/851
    buff = bulkRead(0x82, 0x0E00)
    # Generated from packet 876/876
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 877/877
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 878/878
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 879/879
    buff = bulkRead(0x82, 0x4000)
    # Generated from packet 880/880
    buff = bulkRead(0x82, 0x3200)
    # WARNING: req max 12800 but got 16384
    # WARNING: 26 pending requests


def open_dev(usbcontext=None):
    if usbcontext is None:
        usbcontext = usb1.USBContext()
    
    print 'Scanning for devices...'
    for udev in usbcontext.getDeviceList(skip_on_error=True):
        vid = udev.getVendorID()
        pid = udev.getProductID()
        if (vid, pid) == (0x0661, 0xA802):
            print
            print
            print 'Found device'
            print 'Bus %03i Device %03i: ID %04x:%04x' % (
                udev.getBusNumber(),
                udev.getDeviceAddress(),
                vid,
                pid)
            return udev.open()
    raise Exception("Failed to find a device")

if __name__ == "__main__":
    import argparse 
    
    parser = argparse.ArgumentParser(description='Replay captured USB packets')
    args = parser.parse_args()

    usbcontext = usb1.USBContext()
    dev = open_dev(usbcontext)
    dev.claimInterface(0)
    dev.resetDevice()
    replay(dev)


