# Selected device 8
# Generated by uvusbreplay 0.1
# uvusbreplay copyright 2011 John McMaster <JohnDMcMaster@gmail.com>
# cmd: /home/mcmaster/bin/usbrply --device-hi ham/2019-12-26_02_init.pcapng --wrapper --vid 0x0661 --pid 0xa802

import binascii
import time
import usb1

def validate_read(expected, actual, msg):
    if expected != actual:
        print 'Failed %s' % msg
        print '  Expected; %s' % binascii.hexlify(expected,)
        print '  Actual:   %s' % binascii.hexlify(actual,)
        #raise Exception('failed validate: %s' % msg)


def replay(dev):
    def bulkRead(endpoint, length, timeout=None):
        return dev.bulkRead(endpoint, length, timeout=(1000 if timeout is None else timeout))

    def bulkWrite(endpoint, data, timeout=None):
        dev.bulkWrite(endpoint, data, timeout=(1000 if timeout is None else timeout))
    
    def controlRead(request_type, request, value, index, length,
                    timeout=None):
        return dev.controlRead(request_type, request, value, index, length,
                    timeout=(1000 if timeout is None else timeout))

    def controlWrite(request_type, request, value, index, data,
                     timeout=None):
        dev.controlWrite(request_type, request, value, index, data,
                     timeout=(1000 if timeout is None else timeout))


    # Generated from packet 209/210
    bulkWrite(0x01, "\x00\x00\x00\x00\x00\x00\x00\x00")
    # Generated from packet 211/212
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x01", buff, "packet 211/212")
    # Generated from packet 213/214
    bulkWrite(0x01, "\x00\x00\x00\x01\x00\x00\x00\x00")
    # Generated from packet 215/216
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x48\x41\x4D\x41\x4D\x41\x54\x53\x55\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x43\x39\x37\x33\x30\x44\x4B\x2D\x31\x31\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x31\x2E\x32\x31\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x35\x34\x30\x33\x32\x31\x39\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 215/216")
    # Generated from packet 217/218
    bulkWrite(0x01, "\x00\x00\x00\x02\x00\x00\x00\x00")
    # Generated from packet 219/220
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x00\x14\x00\x00\x04\x08\x00\x00\x04\x08\x00\x00\x00\x10"
            "\x00\x00\x00\x01", buff, "packet 219/220")
    # Generated from packet 221/222
    bulkWrite(0x01, "\x00\x00\x00\x24\x00\x00\x00\x00")
    # Generated from packet 223/224
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x00\x06\x00\x00\x00\x20\x00\x00\x00\x03", buff, "packet 223/224")
    # Generated from packet 225/226
    bulkWrite(0x01, "\x00\x00\x00\x2A\x00\x00\x00\x00")
    # Generated from packet 227/228
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 227/228")
    # Generated from packet 229/230
    bulkWrite(0x01, "\x00\x00\x00\x39\x00\x00\x00\x00")
    # Generated from packet 231/232
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 231/232")
    # Generated from packet 233/234
    bulkWrite(0x01, "\x00\x00\x00\x3A\x00\x00\x00\x00")
    # Generated from packet 235/236
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 235/236")
    # Generated from packet 237/238
    bulkWrite(0x01, "\x00\x00\x00\x3B\x00\x00\x00\x00")
    # Generated from packet 239/240
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 239/240")
    # Generated from packet 241/242
    bulkWrite(0x01, "\x00\x00\x00\x3C\x00\x00\x00\x00")
    # Generated from packet 243/244
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 243/244")
    # Generated from packet 245/246
    bulkWrite(0x01, "\x00\x00\x00\x3D\x00\x00\x00\x00")
    # Generated from packet 247/248
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 247/248")
    # Generated from packet 249/250
    bulkWrite(0x01, "\x00\x00\x00\x4A\x00\x00\x00\x00")
    # Generated from packet 251/252
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 251/252")
    # Generated from packet 253/254
    bulkWrite(0x01, "\x00\x00\x00\x4F\x00\x00\x00\x00")
    # Generated from packet 255/256
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 255/256")
    # Generated from packet 257/258
    bulkWrite(0x01, "\x00\x00\x00\x23\x00\x00\x00\x00")
    # Generated from packet 259/260
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x01", buff, "packet 259/260")
    # Generated from packet 261/262
    bulkWrite(0x01, "\x00\x00\x00\x29\x00\x00\x00\x00")
    # Generated from packet 263/264
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 263/264")
    # Generated from packet 265/266
    bulkWrite(0x01, "\x00\x00\x00\x01\x00\x00\x00\x00")
    # Generated from packet 267/268
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x48\x41\x4D\x41\x4D\x41\x54\x53\x55\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x43\x39\x37\x33\x30\x44\x4B\x2D\x31\x31\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x31\x2E\x32\x31\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x35\x34\x30\x33\x32\x31\x39\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 267/268")
    # Generated from packet 269/270
    bulkWrite(0x01, "\x00\x00\x00\x01\x00\x00\x00\x00")
    # Generated from packet 271/272
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x48\x41\x4D\x41\x4D\x41\x54\x53\x55\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x43\x39\x37\x33\x30\x44\x4B\x2D\x31\x31\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x31\x2E\x32\x31\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x35\x34\x30\x33\x32\x31\x39\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 271/272")
    # Generated from packet 273/274
    bulkWrite(0x01, "\x00\x00\x00\x01\x00\x00\x00\x00")
    # Generated from packet 275/276
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x48\x41\x4D\x41\x4D\x41\x54\x53\x55\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x43\x39\x37\x33\x30\x44\x4B\x2D\x31\x31\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x31\x2E\x32\x31\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x35\x34\x30\x33\x32\x31\x39\x00\x00\x00\x00\x00\x00\x00\x00\x00"
            "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 275/276")
    # Generated from packet 277/278
    bulkWrite(0x01, "\x00\x00\x00\x09\x00\x00\x00\x0A\x00\x01\x00\x00\x00\x00\x04\x08"
            "\x04\x08")
    # Generated from packet 279/280
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x01", buff, "packet 279/280")
    # Generated from packet 281/282
    bulkWrite(0x01, "\x00\x00\x00\x04\x00\x00\x00\x00")
    # Generated from packet 283/284
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x04\x08\x00\x00\x04\x08", buff, "packet 283/284")
    # Generated from packet 285/286
    bulkWrite(0x01, "\x00\x00\x00\x2E\x00\x00\x00\x04\x00\x00\x00\x02")
    # Generated from packet 287/288
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 287/288")
    # Generated from packet 289/290
    bulkWrite(0x01, "\x00\x00\x00\x2E\x00\x00\x00\x04\x00\x00\x00\x12")
    # Generated from packet 291/292
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 291/292")
    # Generated from packet 293/294
    bulkWrite(0x01, "\x00\x00\x00\x2E\x00\x00\x00\x04\x00\x00\x00\x18")
    # Generated from packet 295/296
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 295/296")
    # Generated from packet 297/298
    bulkWrite(0x01, "\x00\x00\x00\x21\x00\x00\x00\x04\x00\x00\x00\x00")
    # Generated from packet 299/300
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x3F\x9E\xB8\x51\xEB\x85\x1E\xB8", buff, "packet 299/300")
    # Generated from packet 301/302
    bulkWrite(0x01, "\x00\x00\x00\x21\x00\x00\x00\x04\x00\x00\x00\x01")
    # Generated from packet 303/304
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x40\x34\x00\x00\x00\x00\x00\x00", buff, "packet 303/304")
    # Generated from packet 305/306
    bulkWrite(0x01, "\x00\x00\x00\x21\x00\x00\x00\x04\x00\x00\x00\x02")
    # Generated from packet 307/308
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x3F\x50\x62\x4D\xD2\xF1\xA9\xFC", buff, "packet 307/308")
    # Generated from packet 309/310
    bulkWrite(0x01, "\x00\x00\x00\x21\x00\x00\x00\x04\x00\x00\x00\x03")
    # Generated from packet 311/312
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x00\x00\x00\x00\x00\x00", buff, "packet 311/312")
    # Generated from packet 313/314
    bulkWrite(0x01, "\x00\x00\x00\x20\x00\x00\x00\x04\x00\x00\x07\xD0")
    # Generated from packet 315/316
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x01", buff, "packet 315/316")
    # Generated from packet 317/318
    bulkWrite(0x01, "\x00\x00\x00\x1F\x00\x00\x00\x00")
    # Generated from packet 319/320
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x07\xD0", buff, "packet 319/320")
    # Generated from packet 321/322
    bulkWrite(0x01, "\x00\x00\x00\x20\x00\x00\x00\x04\x00\x00\x00\xFA")
    # Generated from packet 323/324
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x01", buff, "packet 323/324")
    # Generated from packet 325/326
    bulkWrite(0x01, "\x00\x00\x00\x1F\x00\x00\x00\x00")
    # Generated from packet 327/328
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x00\xFA", buff, "packet 327/328")
    # Generated from packet 329/330
    bulkWrite(0x01, "\x00\x00\x00\x20\x00\x00\x00\x04\x00\x00\x00\xFA")
    # Generated from packet 331/332
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x01", buff, "packet 331/332")
    # Generated from packet 333/334
    bulkWrite(0x01, "\x00\x00\x00\x1F\x00\x00\x00\x00")
    # Generated from packet 335/336
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x00\xFA", buff, "packet 335/336")
    # Generated from packet 337/338
    bulkWrite(0x01, "\x00\x00\x00\x2D\x00\x00\x00\x02\x00\x01")
    # Generated from packet 339/340
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 339/340")
    # Generated from packet 341/342
    bulkWrite(0x01, "\x00\x00\x00\x1F\x00\x00\x00\x00")
    # Generated from packet 343/344
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x00\xFA", buff, "packet 343/344")
    # Generated from packet 345/346
    bulkWrite(0x01, "\x00\x00\x00\x2E\x00\x00\x00\x04\x00\x00\x00\x12")
    # Generated from packet 347/348
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 347/348")
    # Generated from packet 349/350
    bulkWrite(0x01, "\x00\x00\x00\x2E\x00\x00\x00\x04\x00\x00\x00\x02")
    # Generated from packet 351/352
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 351/352")
    # Generated from packet 353/354
    bulkWrite(0x01, "\x00\x00\x00\x20\x00\x00\x00\x04\x00\x00\x00\xFA")
    # Generated from packet 355/356
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x01", buff, "packet 355/356")
    # Generated from packet 357/358
    bulkWrite(0x01, "\x00\x00\x00\x1F\x00\x00\x00\x00")
    # Generated from packet 359/360
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00\x00\x00\xFA", buff, "packet 359/360")
    # Generated from packet 361/362
    bulkWrite(0x01, "\x00\x00\x00\x2D\x00\x00\x00\x02\x00\x01")
    # Generated from packet 363/364
    buff = bulkRead(0x83, 0x0200)
    validate_read("\x00", buff, "packet 363/364")

def open_dev(usbcontext=None):
    if usbcontext is None:
        usbcontext = usb1.USBContext()
    
    print 'Scanning for devices...'
    for udev in usbcontext.getDeviceList(skip_on_error=True):
        vid = udev.getVendorID()
        pid = udev.getProductID()
        if (vid, pid) == (0x0661, 0xA802):
            print
            print
            print 'Found device'
            print 'Bus %03i Device %03i: ID %04x:%04x' % (
                udev.getBusNumber(),
                udev.getDeviceAddress(),
                vid,
                pid)
            return udev.open()
    raise Exception("Failed to find a device")

if __name__ == "__main__":
    import argparse 
    
    parser = argparse.ArgumentParser(description='Replay captured USB packets')
    args = parser.parse_args()

    usbcontext = usb1.USBContext()
    dev = open_dev(usbcontext)
    dev.claimInterface(0)
    dev.resetDevice()
    replay(dev)


